version: "2"

services:
  main:
    build: .
    environment:
      FLASK_APP: main.py
    restart: unless-stopped
    command: flask run --host=0.0.0.0
    networks:
      - default
      - diyscan

networks:
  diyscan:
    external: true
